#!/bin/bash

NAME="jas"                                    #Name of the application (*)

DJANGODIR=/home/ubuntu/jas/env/jas             # Django project directory (*)
SOCKFILE=/home/ubuntu/jas/env/run/gunicorn.sock        # we will communicate using this unix socket (*)
USER=ubuntu                                        # the user to run as (*)
#GROUP=                                     # the group to run as (*)
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn (*)
DJANGO_SETTINGS_MODULE=jas.settings             # which settings file should Django use (*)
DJANGO_WSGI_MODULE=jas.wsgi                     # WSGI module name (*)

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/ubuntu/jas/env/bin/activate
export PATH=$HOME/bin:$PATH
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
export LD_LIBRARY_PATH="/home/ubuntu/lib"

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/ubuntu/jas/env/bin/gunicorn --bind 0.0.0.0:8000 ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user $USER \
  --log-level=debug \
  --log-file=-
